/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as LangIpRouteImport } from './routes/$lang/$ip'
import { Route as ApiIpIpRouteImport } from './routes/api/ip.$ip'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIpRoute = LangIpRouteImport.update({
  id: '/$ip',
  path: '/$ip',
  getParentRoute: () => LangRouteRoute,
} as any)
const ApiIpIpRoute = ApiIpIpRouteImport.update({
  id: '/api/ip/$ip',
  path: '/api/ip/$ip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/$ip': typeof LangIpRoute
  '/api/me': typeof ApiMeRoute
  '/$lang/': typeof LangIndexRoute
  '/api/ip/$ip': typeof ApiIpIpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/$ip': typeof LangIpRoute
  '/api/me': typeof ApiMeRoute
  '/$lang': typeof LangIndexRoute
  '/api/ip/$ip': typeof ApiIpIpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/$ip': typeof LangIpRoute
  '/api/me': typeof ApiMeRoute
  '/$lang/': typeof LangIndexRoute
  '/api/ip/$ip': typeof ApiIpIpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/$ip'
    | '/api/me'
    | '/$lang/'
    | '/api/ip/$ip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang/$ip' | '/api/me' | '/$lang' | '/api/ip/$ip'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/$ip'
    | '/api/me'
    | '/$lang/'
    | '/api/ip/$ip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiIpIpRoute: typeof ApiIpIpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$ip': {
      id: '/$lang/$ip'
      path: '/$ip'
      fullPath: '/$lang/$ip'
      preLoaderRoute: typeof LangIpRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/api/ip/$ip': {
      id: '/api/ip/$ip'
      path: '/api/ip/$ip'
      fullPath: '/api/ip/$ip'
      preLoaderRoute: typeof ApiIpIpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangRouteRouteChildren {
  LangIpRoute: typeof LangIpRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangIpRoute: LangIpRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiIpIpRoute: ApiIpIpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
